import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { toast } from "react-toastify";
import { api } from "../../api/http";
import { getProfileCompletion } from "../../student/profileCompletion";

export default function InternshipDetailPage() {
  const { id } = useParams(); const [item, setItem] = useState(null); const [profile, setProfile] = useState(null); const [coverNote, setCoverNote] = useState(""); const [applying, setApplying] = useState(false);
  useEffect(() => { api(`/internships/${id}`).then(setItem).catch(() => setItem(false)); api("/student/profile").then(setProfile).catch(() => setProfile(false)); }, [id]);
  if (item === false) return <div className="container py-5"><Link to="/student/internships">← Internships</Link><div className="feature-card mt-4"><h1 className="h5">Internship not found</h1></div></div>;
  if (!item) return <div className="container py-5"><p className="text-secondary">Loading internship…</p></div>;
  const profileStatus = getProfileCompletion(profile); const canApply = profileStatus.complete;
  const apply = async (e) => { e.preventDefault(); if (!canApply) return; setApplying(true); try { await api("/applications", { method: "POST", body: JSON.stringify({ internshipId: Number(id), coverNote }) }); toast.success("Application submitted."); setCoverNote(""); } catch (error) { toast.error(error.message); } finally { setApplying(false); } };
  return <div className="container py-5"><Link className="small text-decoration-none" to="/student/internships">← Internships</Link><div className="feature-card mt-4"><div className="eyebrow">{item.domain}</div><h1 className="display-6 fw-semibold mt-3">{item.title}</h1><p className="lead text-secondary">{item.company.name} · {item.location || "Flexible location"}</p><p className="mt-4">{item.description}</p><h2 className="h5 mt-4">Required skills</h2><div className="d-flex flex-wrap gap-2">{item.requiredSkills.map((name) => <span className="badge rounded-pill text-bg-light border p-2" key={name}>{name}</span>)}</div><div className="row mt-4 small text-secondary"><div className="col-sm-4">Work mode<br /><strong className="text-dark">{item.workMode || "Not specified"}</strong></div><div className="col-sm-4">Duration<br /><strong className="text-dark">{item.durationWeeks ? `${item.durationWeeks} weeks` : "Not specified"}</strong></div><div className="col-sm-4">Deadline<br /><strong className="text-dark">{item.applicationDeadline || "Not specified"}</strong></div></div>{profile !== null && !canApply ? <div className="profile-required-callout mt-4"><div><strong>Complete your profile to apply</strong><p className="mb-0 small">Add {profileStatus.missing.slice(0, 3).join(", ")} to unlock applications.</p></div><Link className="btn btn-primary btn-sm" to="/student/profile">Complete profile</Link></div> : <form className="border-top mt-4 pt-4" onSubmit={apply}><label className="form-label">Cover note <span className="text-secondary">(optional)</span></label><textarea className="form-control mb-3" rows="4" maxLength="2000" value={coverNote} onChange={(e) => setCoverNote(e.target.value)} placeholder="Tell the company why this opportunity fits you." /><button className="btn btn-primary" disabled={applying || profile === null}>{applying ? "Submitting…" : "Apply now"}</button></form>}</div></div>;
}
