import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "react-toastify";
import { api } from "../../api/http";

export default function RecommendationsPage() {
  const [items, setItems] = useState([]); const [appliedIds, setAppliedIds] = useState(new Set()); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([api("/recommendations"), api("/applications")]).then(([recommendations, applications]) => { setItems(recommendations.content || []); setAppliedIds(new Set((applications.content || []).map((application) => application.internship.id))); }).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, []);
  return <div className="container py-5"><Link className="small text-decoration-none" to="/student">← Dashboard</Link><div className="eyebrow mt-3">For you</div><h1 className="display-6 fw-semibold">Recommended for your profile.</h1><p className="text-secondary">Every score is explainable: skills, domain, qualification, and interests all contribute.</p>{loading ? <p className="text-secondary mt-5">Calculating your matches…</p> : items.length ? <div className="row g-4 mt-2">{items.map((item) => { const applied = appliedIds.has(item.internship.id); return <div className="col-md-6 col-lg-4" key={item.id}><div className="feature-card recommendation-card h-100"><div className="recommendation-topline"><div className="eyebrow">{item.internship.domain}</div>{applied ? <span className="badge rounded-pill text-bg-secondary">Applied</span> : <span className="match-score">{item.matchScore}%</span>}</div><h2 className="h5 mt-3">{item.internship.title}</h2><p className="small text-secondary">{item.internship.company.name}</p><p className="text-secondary small recommendation-explanation">{item.explanation}.</p><Link className="btn btn-sm btn-outline-primary mt-auto" to={`/student/internships/${item.internship.id}`}>View details →</Link></div></div>; })}</div> : <div className="feature-card mt-4"><h2 className="h5">No recommendations yet</h2><p className="text-secondary mb-0">Add your domain and skills to your profile, then check back here.</p></div>}</div>;
}
