import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "react-toastify";
import { api, uploadFile } from "../../api/http";
import { BRANCH_OPTIONS, QUALIFICATION_OPTIONS } from "../../constants/profileOptions";

export default function StudentProfilePage() {
  const [profile, setProfile] = useState(null); const [skill, setSkill] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { api("/student/profile").then(setProfile).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, []);
  if (loading) return <PageMessage message="Loading your profile…" />; if (!profile) return null;
  const update = (key, value) => setProfile({ ...profile, [key]: value });
  const save = async (e) => { e.preventDefault(); setSaving(true); const { fullName, mobile, domain, qualification, college, graduationYear, interests } = profile; try { setProfile(await api("/student/profile", { method: "PUT", body: JSON.stringify({ fullName, mobile, domain, qualification, college, graduationYear, interests }) })); toast.success("Profile saved."); } catch (error) { toast.error(error.message); } finally { setSaving(false); } };
  const addSkill = async (e) => { e.preventDefault(); if (!skill.trim()) return; try { const added = await api("/student/skills", { method: "POST", body: JSON.stringify({ name: skill }) }); setProfile({ ...profile, skills: [...profile.skills.filter((item) => item.id !== added.id), added] }); setSkill(""); } catch (error) { toast.error(error.message); } };
  const removeSkill = async (id) => { try { await api(`/student/skills/${id}`, { method: "DELETE" }); setProfile({ ...profile, skills: profile.skills.filter((item) => item.id !== id) }); } catch (error) { toast.error(error.message); } };
  const uploadResume = async (event) => { const file = event.target.files[0]; if (!file) return; try { setProfile(await uploadFile("/student/resume", file)); toast.success("Resume uploaded."); } catch (error) { toast.error(error.message); } event.target.value = ""; };
  const deleteResume = async () => { try { await api("/student/resume", { method: "DELETE" }); setProfile({ ...profile, resumeFileName: null, resumeUploadedAt: null }); toast.success("Resume removed."); } catch (error) { toast.error(error.message); } };
  const completion = [profile.fullName, profile.domain, profile.qualification, profile.college, profile.graduationYear, profile.skills.length, profile.resumeFileName].filter(Boolean).length;
  return <div className="container py-5"><BackLink to="/student" label="Dashboard" /><h1 className="display-6 fw-semibold mt-3">Your profile</h1><p className="text-secondary">A stronger profile leads to more relevant recommendations.</p><div className="progress mb-4" role="progressbar" aria-label="Profile completion" aria-valuenow={Math.round(completion / 7 * 100)}><div className="progress-bar" style={{ width: `${Math.round(completion / 7 * 100)}%` }}>{Math.round(completion / 7 * 100)}%</div></div><form className="card border-0 shadow-sm p-4 mt-4" onSubmit={save}><div className="row g-3"><Field label="Full name" required value={profile.fullName || ""} onChange={(e) => update("fullName", e.target.value)} /><Field label="Mobile" value={profile.mobile || ""} onChange={(e) => update("mobile", e.target.value)} /><SelectField label="Domain / branch" value={profile.domain || ""} options={BRANCH_OPTIONS} onChange={(e) => update("domain", e.target.value)} /><SelectField label="Qualification" value={profile.qualification || ""} options={QUALIFICATION_OPTIONS} onChange={(e) => update("qualification", e.target.value)} /><Field label="College / institute" wide value={profile.college || ""} onChange={(e) => update("college", e.target.value)} /><Field label="Graduation year" type="number" value={profile.graduationYear || ""} onChange={(e) => update("graduationYear", e.target.value ? Number(e.target.value) : null)} /><div className="col-12"><label className="form-label">Interests</label><textarea className="form-control" rows="3" value={profile.interests || ""} onChange={(e) => update("interests", e.target.value)} /></div></div><button className="btn btn-primary mt-4" disabled={saving}>{saving ? "Saving…" : "Save profile"}</button></form><div className="card border-0 shadow-sm p-4 mt-4"><h2 className="h5">Resume</h2><p className="text-secondary small">Upload a PDF, DOC, or DOCX file up to 5 MB.</p>{profile.resumeFileName ? <div className="d-flex align-items-center gap-3"><span className="small">{profile.resumeFileName}</span><button type="button" className="btn btn-sm btn-outline-danger" onClick={deleteResume}>Remove</button></div> : <input className="form-control" type="file" accept=".pdf,.doc,.docx" onChange={uploadResume} />}</div><div className="card border-0 shadow-sm p-4 mt-4"><h2 className="h5">Skills</h2><div className="d-flex flex-wrap gap-2 mb-3">{profile.skills.length ? profile.skills.map((item) => <span className="badge rounded-pill text-bg-light border p-2" key={item.id}>{item.name} <button type="button" className="btn-close ms-1" aria-label={`Remove ${item.name}`} onClick={() => removeSkill(item.id)} /></span>) : <span className="text-secondary small">No skills added yet.</span>}</div><form className="d-flex gap-2" onSubmit={addSkill}><input className="form-control" placeholder="Add a skill" value={skill} onChange={(e) => setSkill(e.target.value)} /><button className="btn btn-outline-primary">Add</button></form></div></div>;
}

function SelectField({ label, value, options, onChange }) { return <div className="col-md-6"><label className="form-label">{label}</label><select className="form-select" value={value} onChange={onChange}><option value="">Select {label.toLowerCase()}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></div>; }

function Field({ label, wide, ...props }) { return <div className={wide ? "col-md-8" : "col-md-6"}><label className="form-label">{label}</label><input className="form-control" {...props} /></div>; }
function BackLink({ to, label }) { return <Link className="small text-decoration-none" to={to}>← {label}</Link>; }
function PageMessage({ message }) { return <div className="container py-5"><p className="text-secondary">{message}</p></div>; }
