import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../../api/http";
import { getProfileCompletion } from "../../student/profileCompletion";

export default function StudentDashboardPage() {
  const [profile, setProfile] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { api("/student/profile").then(setProfile).finally(() => setLoading(false)); }, []);
  const progress = getProfileCompletion(profile);
  return <div className="container py-5"><section className="student-hero"><div><div className="eyebrow">Student workspace</div><h1 className="display-6 fw-semibold">Find the right internship, with confidence.</h1><p className="lead text-secondary mb-0">Keep your profile current, discover suitable roles, and track each application in one place.</p></div><div className="profile-summary"><div className="d-flex justify-content-between align-items-start gap-3"><div><span className={`badge rounded-pill ${progress.complete ? "text-bg-success" : "text-bg-primary"}`}>{loading ? "Loading…" : progress.complete ? "Profile complete" : "Profile in progress"}</span><h2 className="h5 mt-3 mb-1">Your profile</h2><p className="small text-secondary mb-0">{loading ? "Checking your details" : progress.complete ? "You’re ready to apply." : `${progress.completed} of ${progress.total} essentials completed`}</p></div><strong className="profile-percentage">{loading ? "—" : `${progress.percentage}%`}</strong></div><div className="progress profile-progress mt-3"><div className="progress-bar" style={{ width: `${loading ? 0 : progress.percentage}%` }} /></div>{!loading && !progress.complete && <p className="small text-secondary mt-3 mb-0">Next: add {progress.missing.slice(0, 2).join(" and ")}.</p>}<Link className="btn btn-primary btn-sm mt-3" to="/student/profile">{progress.complete ? "Review profile" : "Complete profile"}</Link></div></section><section className="student-action-grid mt-4"><article className="student-action-card"><div className="eyebrow">Opportunities</div><h2 className="h4">Explore internships</h2><p className="text-secondary">Search active roles across domains, companies, and work modes.</p><div className="student-card-actions"><Link className="btn btn-primary" to="/student/internships">Browse internships</Link><Link className="btn btn-outline-primary" to="/student/recommendations">View recommendations</Link></div></article><article className="student-action-card"><div className="eyebrow">Applications</div><h2 className="h4">Stay on top of every application</h2><p className="text-secondary">Review submitted applications and see the latest status updates.</p><Link className="btn btn-outline-dark" to="/student/applications">View applications</Link></article></section><p className="student-apply-note mt-4 mb-0">{progress.complete ? "Your completed profile is ready for applications." : "Complete your profile before applying to an internship."}</p></div>;
}
