import { useState } from "react";
import { toast } from "react-toastify";
import { api } from "../../../api/http";

const blank = { name: "", description: "", location: "", industry: "", website: "" };
export default function CompanyManagementPanel({ companies, onChanged }) {
  const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState(null); const [busy, setBusy] = useState(false);
  const update = (key, value) => setForm({ ...form, [key]: value });
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { await api(editingId ? `/admin/companies/${editingId}` : "/admin/companies", { method: editingId ? "PUT" : "POST", body: JSON.stringify(form) }); toast.success(editingId ? "Company updated." : "Company created."); setForm(blank); setEditingId(null); onChanged(); } catch (error) { toast.error(error.message); } finally { setBusy(false); } };
  const edit = (company) => { setEditingId(company.id); setForm({ name: company.name, description: company.description || "", location: company.location || "", industry: company.industry || "", website: company.website || "" }); };
  const deactivate = async (id) => { if (!window.confirm("Deactivate this company?")) return; try { await api(`/admin/companies/${id}`, { method: "DELETE" }); toast.success("Company deactivated."); onChanged(); } catch (error) { toast.error(error.message); } };
  return <div><form className="card border-0 shadow-sm p-4 mb-4" onSubmit={submit}><h2 className="h5">{editingId ? "Edit company" : "Add company"}</h2><div className="row g-3"><Input placeholder="Company name" required value={form.name} onChange={(e) => update("name", e.target.value)} /><Input placeholder="Industry" value={form.industry} onChange={(e) => update("industry", e.target.value)} /><Input placeholder="Location" value={form.location} onChange={(e) => update("location", e.target.value)} /><Input type="url" placeholder="Website" value={form.website} onChange={(e) => update("website", e.target.value)} /><div className="col-12"><textarea className="form-control" rows="2" placeholder="Description" value={form.description} onChange={(e) => update("description", e.target.value)} /></div></div><button className="btn btn-primary mt-3" disabled={busy}>{busy ? "Saving…" : editingId ? "Update company" : "Create company"}</button>{editingId && <button type="button" className="btn btn-link mt-3" onClick={() => { setEditingId(null); setForm(blank); }}>Cancel</button>}</form><div className="admin-company-list">{companies.map((company) => <article className="admin-company-card" key={company.id}><div className="admin-company-main"><div className="admin-company-heading"><h3 className="h6 mb-0">{company.name}</h3>{!company.active && <span className="badge rounded-pill text-bg-secondary">Inactive</span>}</div><div className="small text-secondary">{company.industry || "No industry set"} · {company.location || "No location set"}</div></div><div className="admin-card-actions"><button className="btn btn-sm btn-outline-primary" onClick={() => edit(company)}>Edit</button>{company.active && <button className="btn btn-sm btn-outline-danger" onClick={() => deactivate(company.id)}>Deactivate</button>}</div></article>)}</div></div>;
}
function Input(props) { return <div className="col-md-6"><input className="form-control" {...props} /></div>; }
