import { useState } from "react";
import { toast } from "react-toastify";
import { api } from "../../../api/http";

export default function CompanyManagementPanel({ companies, onChanged }) {
  const [form, setForm] = useState({ name: "", description: "", location: "", industry: "", website: "" }); const [editingId, setEditingId] = useState(null); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { await api(editingId ? `/admin/companies/${editingId}` : "/admin/companies", { method: editingId ? "PUT" : "POST", body: JSON.stringify(form) }); toast.success(editingId ? "Company updated." : "Company created."); setForm({ name: "", description: "", location: "", industry: "", website: "" }); setEditingId(null); onChanged(); } catch (error) { toast.error(error.message); } finally { setBusy(false); } };
  const edit = (company) => { setEditingId(company.id); setForm({ name: company.name, description: company.description || "", location: company.location || "", industry: company.industry || "", website: company.website || "" }); };
  const deactivate = async (id) => { if (!window.confirm("Deactivate this company?")) return; try { await api(`/admin/companies/${id}`, { method: "DELETE" }); toast.success("Company deactivated."); onChanged(); } catch (error) { toast.error(error.message); } };
  return <div><form className="card border-0 shadow-sm p-4 mb-4" onSubmit={submit}><h2 className="h5">{editingId ? "Edit company" : "Add company"}</h2><div className="row g-3"><div className="col-md-6"><input className="form-control" placeholder="Company name" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="col-md-6"><input className="form-control" placeholder="Industry" value={form.industry} onChange={(e) => setForm({ ...form, industry: e.target.value })} /></div><div className="col-md-6"><input className="form-control" placeholder="Location" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></div><div className="col-md-6"><input className="form-control" type="url" placeholder="Website" value={form.website} onChange={(e) => setForm({ ...form, website: e.target.value })} /></div><div className="col-12"><textarea className="form-control" rows="2" placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div></div><button className="btn btn-primary mt-3" disabled={busy}>{busy ? "Saving…" : editingId ? "Update company" : "Create company"}</button>{editingId && <button type="button" className="btn btn-link mt-3" onClick={() => { setEditingId(null); setForm({ name: "", description: "", location: "", industry: "", website: "" }); }}>Cancel</button>}</form>{companies.map((company) => <div className="feature-card py-3 mb-2 d-flex justify-content-between align-items-center gap-3" key={company.id}><div><strong>{company.name}</strong><div className="text-secondary small">{company.industry || "No industry set"} · {company.location || "No location set"}</div></div><div className="d-flex gap-2"><button className="btn btn-sm btn-outline-primary" onClick={() => edit(company)}>Edit</button>{company.active && <button className="btn btn-sm btn-outline-danger" onClick={() => deactivate(company.id)}>Deactivate</button>}</div></div>)}</div>;
}
